name: Gerar Executavel
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Nativefier
        run: npm install -g nativefier

      - name: Criar o Executável
        run: nativefier --name "MeuApp" "https://joabeplay1.github.io/paiz-o-gostoso-andressa-adora-/"

      - name: Upload do arquivo
        uses: actions/upload-artifact@v4
        with:
          name: App-Windows
          path: MeuApp-win32-x64
