name: Gerar Executavel
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Nativefier
        run: npm install -g nativefier

      - name: Criar o Executável
        # Substitua a URL abaixo pelo seu link ou o caminho do arquivo local
        run: nativefier --name "MeuApp" "https://joabeplay1.github.io/paiz-o-gostoso-andressa-adora-/"

      - name: Upload do arquivo
        uses: actions/upload-artifact@v3
        with:
          name: App-Windows
          path: MeuApp-win32-x64
